#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"

set -ex

cargo +nightly run --manifest-path=../../cargo-fuzz/Cargo.toml fuzz "$@"